version: "3.8"
services:
  postgres:
    container_name: postgres_tt
    image: library/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    ports:
      - "5432:5432"
    restart: unless-stopped