server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CoffeeShopDB
    username: postgres
    password: postgres
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true