server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CoffeeShopDB
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml